Repository woowa-techcamp-2021/baemin-18, pull requests merged in 2021-07, with the labels that each got.

#16 [#4] 라우터 구성
  .gitignore
  package-lock.json
  package.json
  src/index.js
  src/routers/join-router.js
  src/routers/login-router.js
  src/views/join.pug
  src/views/login.pug
  src/views/main.pug
Labels: be

#17 [#8] 공통 UI 구현
  src/public/reset.css
  src/public/style.css
Labels: fe

#18 [#8] 공통 UI 구현 - 2
  src/public/style.css
  src/views/blocks/header.pug
  src/views/main.pug
Labels: fe

#26 [#6] 회원가입 구현
  package-lock.json
  package.json
  src/routers/join-router.js
Labels: be

#27 [#12] 회원가입 2/3 페이지 UI 및 기능 구현
  src/js/join-phone.js
  src/public/join-phone.css
  src/public/style.css
  src/views/join-phone.pug
  src/views/mixins/input-block.pug
Labels: fe

#28 [#7] login router 구현
  src/routers/login-router.js
Labels: be

#44 [#42] 마무리 작업 및 배포
  README.md
  src/js/join-agree.js
  src/js/join-info.js
  src/js/join-phone.js
  src/public/join-phone.css
  src/routers/login-router.js
Labels: be, bug, fe, fix

#46 [#43] 로그아웃 프론트 UI 및 기능 구현
  src/js/main.js
  src/public/main.css
  src/views/main.pug
Labels: fe

#47 [#42] 마무리 작업 및 배포 - 2
  src/js/join-info.js
  src/js/main.js
  src/public/join-agree.css
  src/public/style.css
  src/routers/main-router.js
  src/views/main.pug
Labels: be, bug, fe, fix

#49 [#42] 마무리 작업 및 배포 - 3, UI 수정 및 로딩, 중복검사 구현
  src/js/join-agree.js
  src/js/join-info.js
  src/js/join-phone.js
  src/js/main.js
  src/public/join-agree.css
  src/public/join-info.css
  src/public/join-phone.css
  src/public/style.css
  src/views/join-agree.pug
  src/views/join-info.pug
  src/views/join-phone.pug
Labels: bug, fe, fix

#51 [#42] 마무리
  src/apis/token.js
  src/js/join-info.js
  src/middleware/auth.js
  src/routers/join-router.js
Labels: be, bug, fix

#55 [#54] 타입스크립트 마이그레이션 - 프론트엔드
  .gitignore
  package-lock.json
  package.json
  src/index.ts
  src/js/error.ts
  src/js/join-agree.ts
  src/js/join-info.ts
  src/js/join-phone.ts
  src/js/login.js
  src/js/login.ts
  src/js/main.ts
  tsconfig.json
Labels: fe

#56 [#54] 버그 픽스
  package-lock.json
  package.json
  src/js/join-phone.ts
Labels: fix
